spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/validacion_academica}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        # dialect eliminado - Hibernate lo detecta automáticamente
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
